import {
  mdiBasket,
  mdiBeach,
  mdiBed,
  mdiBriefcase,
  mdiCart,
  mdiFoodForkDrink,
  mdiGasStation,
  mdiHairDryer,
  mdiHanger,
  mdiHome,
  mdiHospitalBuilding,
  mdiMonitorCellphone,
  mdiPartyPopper,
  mdiReceiptTextOutline,
  mdiRoadVariant,
  mdiShieldHalfFull,
  mdiTrainCar,
} from '@mdi/js'

export const IconMap = {
  'food-fork-drink': mdiFoodForkDrink,
  cart: mdiCart,
  hanger: mdiHanger,
  'train-car': mdiTrainCar,
  'monitor-cellphone': mdiMonitorCellphone,
  home: mdiHome,
  'gas-station': mdiGasStation,
  'hospital-building': mdiHospitalBuilding,
  basket: mdiBasket,
  'party-popper': mdiPartyPopper,
  'receipt-text-outline': mdiReceiptTextOutline,
  'hair-dryer': mdiHairDryer,
  'shield-half-full': mdiShieldHalfFull,
  'road-variant': mdiRoadVariant,
  bed: mdiBed,
  beach: mdiBeach,
  briefcase: mdiBriefcase
}
