import {
  mdiAccountArrowRight,
  mdiBankTransfer,
  mdiBasket,
  mdiBeach,
  mdiBed,
  mdiBriefcase,
  mdiCart,
  mdiCashMinus,
  mdiCashRefund,
  mdiCreditCardClock,
  mdiCreditCardRefund,
  mdiDumbbell,
  mdiFilmstrip,
  mdiFoodForkDrink,
  mdiFoodTakeoutBox,
  mdiFoodTurkey,
  mdiGasStation,
  mdiGift,
  mdiHairDryer,
  mdiHandCoin,
  mdiHanger,
  mdiHome,
  mdiHospitalBuilding,
  mdiMeterElectricOutline,
  mdiMonitorCellphone,
  mdiOfficeBuildingCog,
  mdiPartyPopper,
  mdiPercent,
  mdiPiggyBank,
  mdiReceiptTextOutline,
  mdiRoadVariant,
  mdiSchool,
  mdiShieldHalfFull,
  mdiTrainCar,
  mdiWeb,
  mdiYoutubeSubscription,
} from "@mdi/js";

export const IconMap: { [key: string]: string } = {
  "food-turkey": mdiFoodTurkey,
  "food-fork-drink": mdiFoodForkDrink,
  "bank-transfer": mdiBankTransfer,
  "cash-minus": mdiCashMinus,
  cart: mdiCart,
  hanger: mdiHanger,
  "train-car": mdiTrainCar,
  "monitor-cellphone": mdiMonitorCellphone,
  home: mdiHome,
  "gas-station": mdiGasStation,
  "hospital-building": mdiHospitalBuilding,
  basket: mdiBasket,
  "party-popper": mdiPartyPopper,
  "receipt-text-outline": mdiReceiptTextOutline,
  "hair-dryer": mdiHairDryer,
  "shield-half-full": mdiShieldHalfFull,
  "road-variant": mdiRoadVariant,
  "credit-card-clock": mdiCreditCardClock,
  "credit-card-refund": mdiCreditCardRefund,
  "cash-refund": mdiCashRefund,
  "hand-coin": mdiHandCoin,
  "youtube-subscription": mdiYoutubeSubscription,
  "office-building-cog": mdiOfficeBuildingCog,
  "meter-electric-outline": mdiMeterElectricOutline,
  "account-arrow-right": mdiAccountArrowRight,
  "piggy-bank": mdiPiggyBank,
  "food-takeout-box": mdiFoodTakeoutBox,
  percent: mdiPercent,
  filmstrip: mdiFilmstrip,
  gift: mdiGift,
  web: mdiWeb,
  dumbbell: mdiDumbbell,
  school: mdiSchool,
  bed: mdiBed,
  beach: mdiBeach,
  briefcase: mdiBriefcase,
};
