PRAGMA foreign_keys=on;
DROP TABLE IF EXISTS "Transaction";
DROP TABLE IF EXISTS "Account";
DROP TABLE IF EXISTS "Category";
DROP TABLE IF EXISTS "AccountType";
CREATE TABLE IF NOT EXISTS "Transaction" ( "Id" INTEGER PRIMARY KEY, "Amount" INTEGER NOT NULL, "CategoryId" INTEGER NOT NULL, "Notes" VARCHAR(8000) NULL, "PayeeId" INTEGER NULL, "FromAccountId" INTEGER NULL, "ToAccountId" INTEGER NULL, FOREIGN KEY(CategoryId) REFERENCES Category (id), FOREIGN KEY(PayeeId) REFERENCES Payee (id), FOREIGN KEY(FromAccountId) REFERENCES Account (id), FOREIGN KEY(ToAccountId) REFERENCES Account (id));
CREATE TABLE IF NOT EXISTS "Account" ( "Id" INTEGER PRIMARY KEY, "AccountTypeId" INTEGER NOT NULL, "Balance" INTEGER NOT NULL, "Name" VARCHAR(50), FOREIGN KEY(AccountTypeId) REFERENCES AccountType (id));
CREATE TABLE IF NOT EXISTS "Category" ( "Id" INTEGER PRIMARY KEY, "Name" VARCHAR(50));
CREATE TABLE IF NOT EXISTS "AccountType" ( "Id" INTEGER PRIMARY KEY, "Name" VARCHAR(50));
