#! /bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${DATABASE_USER} WITH PASSWORD '${DATABASE_USER_PASSWORD}';
	CREATE DATABASE ${DATABASE_NAME};
	GRANT ALL PRIVILEGES ON DATABASE ${DATABASE_NAME} TO ${DATABASE_USER};
	\c ${DATABASE_NAME} postgres
	GRANT ALL ON SCHEMA public TO ${DATABASE_USER};
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DATABASE_USER};
EOSQL